name: WPScan con Email

on:
  schedule:
    - cron: '0 6 * * 1'
  workflow_dispatch:

jobs:
  scan-and-email:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Instalar WPScan
        run: sudo gem install wpscan

      - name: Ejecutar escaneo
        env:
          WPSCAN_API_TOKEN: ${{ secrets.WPSCAN_API_TOKEN }}
        run: ./wpscan-script.sh

      - name: Enviar email con reporte
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.EMAIL_USER }}
          password: ${{ secrets.EMAIL_PASS }}
          subject: "Reporte WPScan - nasini.com.ar"
          to: ${{ secrets.EMAIL_TO }}
          from: ${{ secrets.EMAIL_USER }}
          content_type: text/plain
          body: |
            Adjuntamos el informe de vulnerabilidades detectadas en https://www.nasini.com.ar.
            Revisión automática generada por GitHub Actions.
          attachments: wpscan-results.txt
